import {StyleSheet, Platform, Dimensions} from 'react-native';
//import {constants} from '../../helpers';
const screenHeight = Dimensions.get('window').height;

const styles = StyleSheet.create({
  // emptyButton: {
  //   borderRadius: 30,
  //   height: 60,
  //   width: 60,
  //   alignContent: 'center',
  //   alignItems: 'center',
  //   justifyContent: 'center',
  //   backgroundColor: constants.appThemeColor,
  // },
  // emptyButtonbg: {
  //   // alignSelf: 'center',
  //   right: 20,
  //   bottom: 20,
  //   position: 'absolute',
  //   borderRadius: 30,
  //   height: 60,
  //   width: 60,
  //   alignContent: 'center',
  //   alignItems: 'center',
  //   justifyContent: 'center',
  //   backgroundColor: constants.appThemeColor,
  // },
  // emptyIcon: {
  //   width: 20,
  //   height: 20,
  //   color: 'white',
  // },
  // onlyPadding: {paddingLeft: 40},
  // onlyFlex: {flex: 1},
  // nextButtonS: {
  //   height: 45,
  //   borderRadius: 6,
  //   justifyContent: 'center',
  //   backgroundColor: constants.white,
  //   fontSize: 14,
  //   fontFamily: constants.muli_semi_bold,
  //   marginLeft: 10,
  // },
  // buttonFloatTextStyle: {
  //   fontSize: 14,
  //   fontFamily: constants.muli_bold,
  //   color: 'white',
  //   textAlign: 'center',
  // },
  // buttonStyleFlat: {
  //   borderRadius: 6,
  //   height: 45,
  //   marginTop: 65,
  //   justifyContent: 'center',
  //   alignItems: 'center',
  //   alignSelf: 'center',
  //   width: 180,
  //   position: 'absolute',
  // },
  // arrowButtonS: {
  //   borderWidth: 1,
  //   borderColor: constants.textInputBorderColor,
  //   height: 45,
  //   borderRadius: 6,
  //   width: 45,
  //   justifyContent: 'center',
  //   backgroundColor: 'white',
  //   alignItems: 'center',
  // },
  // mainView: {
  //   backgroundColor: 'white',
  //   position: 'absolute',
  //   top: 0,
  //   bottom: 0,
  //   left: 0,
  //   right: 0,
  //   margin: 2,
  //   borderRadius: 6,
  //   justifyContent: 'center',
  // },
  // buttonStyle: {
  //   marginTop: 20,
  //   minHeight: 52,
  //   marginRight: 20,
  //   borderRadius: 6,
  //   marginLeft: 20,
  //   justifyContent: 'center',
  // },
  // buttonLeft: {
  //   flex: 1,
  //   justifyContent: 'center',
  //   alignItems: 'center',
  // },
  // buttonInternalContainer: {
  //   height: 52,
  //   borderRadius: 6,
  //   justifyContent: 'center',
  //   width: '100%',
  // },
  // buttonFloatInternalContainer: {
  //   height: 45,
  //   borderRadius: 6,
  //   justifyContent: 'center',
  //   width: '100%',
  // },
  // buttonContainer: {
  //   width: '90%',
  //   flex: 1,
  //   flexDirection: 'row',
  //   overflow: Platform.OS === 'ios' ? 'visible' : 'hidden',
  //   height: 52,
  //   marginLeft: 20,
  //   borderRadius: 6, //30
  //   shadowOpacity: 0.35,
  //   shadowOffset: {
  //     width: -1,
  //     height: 5,
  //   },
  //   shadowColor: 'black',
  //   shadowRadius: 4,
  //   elevation: 5,
  //   position: 'absolute',
  //   alignItems: 'center',
  //   bottom: 15,
  //   alignSelf: 'center',
  // },
  // buttonContainerFloat: {
  //   flex: 1,
  //   flexDirection: 'row',
  //   overflow: Platform.OS === 'ios' ? 'visible' : 'hidden',
  //   height: 45,
  //   width: 160,
  //   borderRadius: 6,
  //   shadowOpacity: 0.35,
  //   shadowOffset: {
  //     width: -1,
  //     height: 5,
  //   },
  //   shadowColor: 'black',
  //   shadowRadius: 4,
  //   elevation: 5,
  //   position: 'absolute',
  //   alignItems: 'center',
  //   bottom: 15,
  //   alignSelf: 'center',
  // },
  // buttonStyleHeight: {
  //   width: '50%',
  //   marginTop: 20,
  //   minHeight: 90,
  //   borderRadius: 6,
  //   marginLeft: 20,
  //   justifyContent: 'center',
  //   alignItems: 'center',
  // },
  // buttonTextStyle: {
  //   textAlign: 'center',
  // },
  // buttonTextStyleDefault: {
  //   textAlign: 'center',
  // },
  // buttonText: {
  //   fontFamily: constants.muli_semi_bold,
  //   fontSize: 14,
  //   color: '#078dff',
  //   textAlign: 'center',
  // },
});

export default styles;
